version: '3.8'

networks:
  jenkins_net:
    external: true

services:
  jenkins:
    image: jenkins/jenkins:2.443-jdk17
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_net
    volumes:
      - "/mnt/jenkins_compose/jenkins_configuration:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /usr/bin/docker:/usr/bin/docker  # Mount the Docker binary from the host

  agent:
    #image: jenkins/ssh-agent:jdk17
    build:
      context: .
      dockerfile: Dockerfile_Agent
      args:
        JENKINS_AGENT_SSH_PUBKEY: ${JENKINS_AGENT_SSH_PUBKEY}
    image: custom-ssh-agent:jdk17
    privileged: true
    user: root
    restart: always
    container_name: agent-docker-aws
    ports:
      - "2223:22"
    #expose:
      #- 22
    networks:
      - jenkins_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /usr/bin/docker:/usr/bin/docker
      #- /usr/local/bin/aws:/usr/bin/aws
    environment:
      #- JENKINS_AGENT_SSH_PUBKEY=ssh-ed2@DevOps
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
      #export JENKINS_AGENT_SSH_PUBKEY=ssh-ed2 @DevOps