version: '3.8'

networks:
  jenkins_net:
    external: true

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-with-awscli
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    networks:
      - jenkins_net
    volumes:
      - "/mnt/jenkins_compose/jenkins_configuration:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /usr/bin/docker:/usr/bin/docker  # Mount the Docker binary from the host

  # agent:
  #   image: jenkins/ssh-agent:jdk17
  #   privileged: true
  #   user: root
  #   restart: always
  #   container_name: agent-docker
  #   expose:
  #     - 22
  #   networks:
  #     - jenkins_net
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - /usr/bin/docker:/usr/bin/docker
  #   environment:
  #     - JENKINS_AGENT_SSH_PUBKEY=ssh- DevOps