services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    ports:
      - "3000:80"
    networks:
      - dev_network
    restart: unless-stopped

  nginx:
    image: nginx:1.26.0-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dev_network
    restart: unless-stopped
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data//nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app

networks:
  dev_network:
    driver: bridge
